src/Entity/Question.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\QuestionRepository")
 */
class Question
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $question_name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Files", mappedBy="fk_question", orphanRemoval=true)
     * @ORM\JoinColumn(nullable=true)
     */
    private $files;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\GroupList", inversedBy="questions")
     * @ORM\JoinColumn(nullable=true)
     */
    private $fk_group;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\AnswerOption", mappedBy="fk_question", orphanRemoval=true, cascade={"persist"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $answeroptions;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ParticipantAnswer", mappedBy="fk_question")
     * @ORM\JoinColumn(nullable=true)
     */
    private $participantAnswers;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\QuestionAttribute", mappedBy="fk_question", orphanRemoval=true)
     * @ORM\JoinColumn(nullable=true)
     */
    private $questionAttributes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TestQuestion", orphanRemoval=true, mappedBy="fk_question")
     * @ORM\JoinColumn(nullable=true)
     */
    private $testQuestions;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $question_wording;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="questions")
     * @ORM\JoinColumn(nullable=true)
     */
    private $fk_user;

    /**
     * @ORM\Column(type="boolean")
     */
    private $required = false;

    public function __construct( )
    {
        $this->files = new ArrayCollection();
        $this->answeroptions = new ArrayCollection();
        $this->participantAnswers = new ArrayCollection();
        $this->questionAttributes = new ArrayCollection();
        $this->testQuestions = new ArrayCollection();
    }

    public function __toString(){
        if ($this->getFkGroup() == null) {
            return (string) $this->question_name;
        }
        else {
            return (string) $this->getFkGroup()->getName() . ' : ' . $this->question_name;
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuestionName(): ?string
    {
        return $this->question_name;
    }

    public function setQuestionName(string $question_name): self
    {
        $this->question_name = $question_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection|Files[]
     */
    public function getFileS(): Collection
    {
        return $this->files;
    }

    public function addFile(Files $file): self
    {
        if (!$this->files->contains($file)) {
            $this->files[] = $file;
            $file->setFkQuestion($this);
        }

        return $this;
    }

    public function removeFile(Files $file): self
    {
        if ($this->files->contains($file)) {
            $this->files->removeElement($file);
            // set the owning side to null (unless already changed)
            if ($file->getFkQuestion() === $this) {
                $file->setFkQuestion(null);
            }
        }

        return $this;
    }

    public function getFkGroup(): ?groupList
    {
        return $this->fk_group;
    }

    public function setFkGroup(?groupList $fk_group): self
    {
        $this->fk_group = $fk_group;

        return $this;
    }

    /**
     * @return Collection|AnswerOption[]
     */
    public function getAnsweroptions(): Collection
    {
        return $this->answeroptions;
    }


    public function addAnsweroption(AnswerOption $answeroption) : self
    {
        if (!$this->answeroptions->contains($answeroption)) {
            $answeroption->setFkQuestion($this);
            $this->answeroptions->add($answeroption);
        }
        return $this;
    }

    public function removeAnsweroption(AnswerOption $answeroption): self
    {
        if ($this->answeroptions->contains($answeroption)) {
            $this->answeroptions->removeElement($answeroption);
            // set the owning side to null (unless already changed)
            if ($answeroption->getFkQuestion() === $this) {
                $answeroption->setFkQuestion(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ParticipantAnswer[]
     */
    public function getParticipantAnswers(): Collection
    {
        return $this->participantAnswers;
    }

    public function addParticipantAnswer(ParticipantAnswer $participantAnswer): self
    {
        if (!$this->participantAnswers->contains($participantAnswer)) {
            $this->participantAnswers[] = $participantAnswer;
            $participantAnswer->setFkQuestion($this);
        }

        return $this;
    }

    public function removeParticipantAnswer(ParticipantAnswer $participantAnswer): self
    {
        if ($this->participantAnswers->contains($participantAnswer)) {
            $this->participantAnswers->removeElement($participantAnswer);
            // set the owning side to null (unless already changed)
            if ($participantAnswer->getFkQuestion() === $this) {
                $participantAnswer->setFkQuestion(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|QuestionAttribute[]
     */
    public function getQuestionAttributes(): Collection
    {
        return $this->questionAttributes;
    }

    public function addQuestionAttribute(QuestionAttribute $questionAttribute): self
    {
        if (!$this->questionAttributes->contains($questionAttribute)) {
            $this->questionAttributes[] = $questionAttribute;
            $questionAttribute->setFkQuestion($this);
        }

        return $this;
    }

    public function removeQuestionAttribute(QuestionAttribute $questionAttribute): self
    {
        if ($this->questionAttributes->contains($questionAttribute)) {
            $this->questionAttributes->removeElement($questionAttribute);
            // set the owning side to null (unless already changed)
            if ($questionAttribute->getFkQuestion() === $this) {
                $questionAttribute->setFkQuestion(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection|TestQuestion[]
     */
    public function getTestQuestions(): Collection
    {
        return $this->testQuestions;
    }

    public function addTestQuestion(TestQuestion $testQuestion): self
    {
        if (!$this->testQuestions->contains($testQuestion)) {
            $this->testQuestions[] = $testQuestion;
            $testQuestion->setFkQuestion($this);
        }

        return $this;
    }

    public function removeTestQuestion(TestQuestion $testQuestion): self
    {
        if ($this->testQuestions->contains($testQuestion)) {
            $this->testQuestions->removeElement($testQuestion);
            // set the owning side to null (unless already changed)
            if ($testQuestion->getFkQuestion() === $this) {
                $testQuestion->setFkQuestion(null);
            }
        }

        return $this;
    }

    public function getQuestionWording(): ?string
    {
        return $this->question_wording;
    }

    public function setQuestionWording(string $question_wording): self
    {
        $this->question_wording = $question_wording;

        return $this;
    }

    public function getFkUser(): ?User
    {
        return $this->fk_user;
    }

    public function setFkUser(?User $fk_user): self
    {
        $this->fk_user = $fk_user;

        return $this;
    }

    public function getRequired(): ?bool
    {
        return $this->required;
    }

    public function setRequired(bool $required): self
    {
        $this->required = $required;

        return $this;
    }

}

src/Form/QuestionType.php
<?php

namespace App\Form;

use App\Entity\AnswerOption;
use App\Entity\GroupList;
use App\Entity\Question;
use App\Entity\QuestionAttribute;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuestionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('question_name', TextType::class, [
                'label'=> 'question.form.question_name_label',
                'attr' => ['placeholder' => 'question.form.question_input_placeholder', 'maxlength' => 255],
                'required' => true,
            ])
            ->add('question_wording',TextareaType::class, [
                'label'=> 'question.form.question_wording_label',
                'attr' => ['placeholder' => 'question.form.question_wording_input_placeholder'],
                'required' => true,
            ])
            ->add('description',TextareaType::class, [
                'label'=> 'question.form.description_label',
                'attr' => ['placeholder' => 'question.form.description_input_placeholder'],
                'required' => false,
            ])
            ->add('type', ChoiceType::class, [
                'label'=> 'question.form.type_label',
                'placeholder' => 'question.form.type_input_placeholder',
                'required' => true,
                'choices' => [
                    'question.type.open' => 'open',
                    'question.type.one' => 'one',
                    'question.type.multi' => 'multi',
                    'question.type.presentation' => 'presentation',
                ],
            ])
            ->add('fk_group', EntityType::class, [
                'label'=> 'question.form.fk_group_label',
                'class' => GroupList::class,
                'placeholder' => 'question.form.fk_group_input_placeholder',
                'required' => false,
                'choice_label' => 'name',
                 'multiple' => false,
                 'expanded' => false,
            ] )
             ->add('answeroptions', CollectionType::class, [
                'entry_type' => AnswerOptionType::class,
                'label' => false,
                'allow_add' => true,
                'entry_options' => ['label' => false],
                'by_reference' => false,
                'allow_delete' => true,
            ])
            ->add('required', CheckboxType::class, [
                'label' => 'question.form.required_description',
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Question::class,
        ]);
    }
}

templates/question/_delete_form.html.twig
<form class="w-49-5" method="post" action="{{ path('question_delete', {'id': question.id}) }}">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ question.id) }}">
    <button class="btn btn-block btn-outline-danger btn-no-right-radius">{{ 'button.delete'|trans }}</button>
</form>
<button data-dismiss="modal" class="w-49-5 btn btn-block btn-primary btn-no-left-radius">{{ 'button.cancel'|trans }}</button>

templates/question/edit.html.twig
{% extends 'admin.html.twig' %}

{% block title %} {{ 'question.title.edit'|trans }} | ETS{% endblock %}

{% block admin_right_nav %}

    <ul class="section-nav">
        <li class="toc-entry">
            <p>{{ 'side_nav.navigation'|trans }}:</p>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-general" data-target="#home" data-target-animation="#questionCaret1" aria-controls="home">{{ 'general'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-groups" data-target="#groups" data-target-animation="#questionCaret2" aria-controls="groups">{{ 'groups'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-answers" data-target="#answers" data-target-animation="#questionCaret3" aria-controls="answers">{{ 'answers'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-time" data-target="#time" data-target-animation="#questionCaret4" aria-controls="time">{{ 'time'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-buttonColor" data-target="#buttonColor" data-target-animation="#questionCaret5" aria-controls="buttonColor">{{ 'buttoncolor'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-backgroundColor" data-target="#backgroundColor" data-target-animation="#questionCaret6" aria-controls="backgroundColor">{{ 'backgroundcolor'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-displayTime" data-target="#displayTime" data-target-animation="#questionCaretDT" aria-controls="displayTime">{{ 'displaytime'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-picture" data-target="#picture" data-target-animation="#questionCaret7" aria-controls="picture">{{ 'picture'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-save">{{ 'button.save'|trans }}</a>
        </li>
        <div class="my-3"></div>
        <li class="toc-entry">
            <a href="" data-toggle="modal" data-target="#questionModal{{ question.id }}Delete" class="modal-append-show badge badge-danger text-white py-1">{{ 'question.button.delete'|trans }}</a>

            <div class="modal fade" id="questionModal{{ question.id }}Delete" tabindex="-1" role="dialog" aria-labelledby="questionModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="questionModalLabel">{{ 'question.delete_message'|trans }}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <span> {{ 'question.delete_helper'|trans }}</span>
                        </div>
                        <div class="modal-footer">
                            <div class="w-100 d-flex justify-content-between">
                                {{ include('question/_delete_form.html.twig') }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </li>
    </ul>
{% endblock %}

{% block admin_main %}

    <h1>{{ 'question.title.edit'|trans  }}</h1>
    {{ include('question/_form.html.twig', {'button_label': 'button.save'}) }}

{% endblock %}

templates/question/index.html.twig
{% extends 'admin.html.twig' %}

{% block title %} {{ 'question.title.index'|trans }} | ETS{% endblock %}

{% block admin_right_nav %}
    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="alert alert-{{ label }}">
                <button type="button" class=" close" data-dismiss="alert" aria-label="Close">
                    <span class="pl-2" aria-hidden="true">&times;</span>
                </button>
                <span class='alert-message'>{{ message|trans }}</span>
            </div>
        {% endfor %}
    {% endfor %}
     <ul class="section-nav">

         {{ include('group/index.html.twig') }}

         <div class="my-3"></div>

         {{ include('group/new.html.twig') }}
     </ul>
{% endblock %}

{% block admin_main %}
    <h1>{{ 'question.title.index'|trans }}</h1>
    <div class="table-responsive table-header-sticky">
        <table id="tableheader" class="table table-borderless bg-blue mb-0 text-white table-header table-index">
            <thead>
                <tr>
                    <th scope="col" colspan="2">
                        <span>{{ 'question.form.question_name_label'|trans }}</span>
                        <a class="text-light" href="{{ path('question_index', { 'slug':'question_name' , 'sort': data['question_name'] }) }}">
                            <i id="questionIndexCaret1" data-toggle="tooltip" data-placement="right" title="{{ 'poppers.sort.name'|trans }}" class="px-2 questionSort pointer fa {{ data['question_name'] }}"></i>
                        </a>
                    </th>
                    <th scope="col">
                        <span>{{ 'question.form.type_label'|trans }}</span>
                        <a class="text-light" href="{{ path('question_index', { 'slug':'type' , 'sort':data['type'] }) }}">
                            <i id="questionIndexCaret2" data-toggle="tooltip" data-placement="right" title="{{ 'poppers.sort.type'|trans }}" class="px-2 questionSort pointer fa {{ data['type'] }}"></i>
                        </a>
                    </th>
                    <th scope="col">
                        <span>{{ 'question.form.fk_group_label'|trans }}</span>
                        <a class="text-light" href="{{ path('question_index', { 'slug':'group' , 'sort':data['group'] }) }}">
                            <i id="questionIndexCaret3" data-toggle="tooltip" data-placement="right" title="{{ 'poppers.sort.group'|trans }}" class="px-2 questionSort pointer fa {{  data['group'] }}"></i>
                        </a>
                    </th>
                    <th scope="col">{{ 'actions'|trans }}</th>
                </tr>
            </thead>
        </table>
    </div>

    <div class="table-responsive">
        <table class="table table-borderless mb-0 table-index">
            <tbody>
            {% for question in questions %}
                    <tr>
                        <td colspan="2">
                            <p>{{ question.questionname|trans }}</p>
                        </td>
                        <td>
                            <p>{{ question.type|trans }}</p>
                        </td>
                        <td>
                            <p>
                            {% if question.fkGroup is null %}
                                <i>{{ 'blank'|trans }}</i>
                            {% else %}
                                {{ question.fkGroup.name }}
                            {% endif %}
                            </p>
                        </td>
                        <td class="d-flex justify-content-around">
                            <a data-toggle="tooltip" data-placement="right" title="{{ 'poppers.edit'|trans }}"  href="{{ path('question_edit', {'id': question.id}) }}"><i class="fa fa-pencil"></i></a>
                            <a data-toggle="tooltip" data-placement="right" title="{{ 'poppers.example'|trans }}" href="{{ path('question_show_example', {'id': question.id}) }}" target="_blank" rel="noopener noreferrer"><i class="fa fa-eye"></i></a>
                            <a data-toggle="tooltip" data-placement="right" title="{{ 'poppers.copy'|trans }}"  href="{{ path('question_copy', {'id': question.id}) }}"><i class="fa fa-copy"></i></a>
                            <a data-toggle="tooltip" data-placement="right" title="{{ 'poppers.show'|trans }}"  href="{{ path('question_show', {'id': question.id}) }}"><i class="fa fa-file-o"></i></a>
                            <a data-tooltip="tooltip" data-placement="right" title="{{ 'poppers.delete'|trans }}"  href="" data-toggle="modal" data-target="#questionModal{{ question.id }}Delete"><i class="fa fa-trash"></i></a>

                            <div class="modal fade" id="questionModal{{ question.id }}Delete" tabindex="-1" role="dialog" aria-labelledby="questionModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="questionModalLabel">{{ 'question.delete_message'|trans }}</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <span> {{ 'question.delete_helper'|trans }}</span>
                                        </div>
                                        <div class="modal-footer">
                                            <div class="w-100 d-flex justify-content-between">
                                                {{ include('question/_delete_form.html.twig') }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>

            {% else %}
                <tr class="text-center">
                    <td colspan="7"><i>{{ 'empty'|trans }}</i></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

templates/question/new.html.twig
{% extends 'admin.html.twig' %}

{% block title %} {{ 'question.title.new'|trans }} | ETS{% endblock %}

{% block admin_right_nav %}
    <ul class="section-nav">
        <li class="toc-entry">
            <p>{{ 'side_nav.navigation'|trans }}:</p>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-general" data-target="#home" data-target-animation="#questionCaret1" aria-controls="home">{{ 'general'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-groups" data-target="#groups" data-target-animation="#questionCaret2" aria-controls="groups">{{ 'groups'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-answers" data-target="#answers" data-target-animation="#questionCaret3" aria-controls="answers">{{ 'answers'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-time" data-target="#time" data-target-animation="#questionCaret4" aria-controls="time">{{ 'time'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-buttonColor" data-target="#buttonColor" data-target-animation="#questionCaret5" aria-controls="buttonColor">{{ 'buttoncolor'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-backgroundColor" data-target="#backgroundColor" data-target-animation="#questionCaret6" aria-controls="backgroundColor">{{ 'backgroundcolor'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-displayTime" data-target="#displayTime" data-target-animation="#questionCaretDT" aria-controls="displayTime">{{ 'displaytime'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-picture" data-target="#picture" data-target-animation="#questionCaret7" aria-controls="picture">{{ 'picture'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-save">{{ 'button.new'|trans }}</a>
        </li>
    </ul>
{% endblock %}

{% block admin_main %}

    <h1>{{ 'question.title.new'|trans }}</h1>
    {{ include('question/_form.html.twig', {'button_label': 'button.new'}) }}

{% endblock %}