src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string", nullable=true)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Question", mappedBy="fk_user", cascade={"persist"})
     */
    private $questions;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Test", mappedBy="fk_user", cascade={"persist"})
     */
    private $tests;

    /**
     * @ORM\Column(type="string")
     */
    private $activation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reset;


    public function __construct()
    {
        $this->questions = new ArrayCollection();
        $this->tests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(?string $password): self
    {
        if ($password != null) {
            $this->password = $password;
        }
        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return Collection|Question[]
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
            $question->setFkUser($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->contains($question)) {
            $this->questions->removeElement($question);
            // set the owning side to null (unless already changed)
            if ($question->getFkUser() === $this) {
                $question->setFkUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Test[]
     */
    public function getTests(): Collection
    {
        return $this->tests;
    }

    public function addTest(Test $test): self
    {
        if (!$this->tests->contains($test)) {
            $this->tests[] = $test;
            $test->setFkUser($this);
        }

        return $this;
    }

    public function removeTest(Test $test): self
    {
        if ($this->tests->contains($test)) {
            $this->tests->removeElement($test);
            // set the owning side to null (unless already changed)
            if ($test->getFkUser() === $this) {
                $test->setFkUser(null);
            }
        }

        return $this;
    }

    public function getActivation(): ?string
    {
        return $this->activation;
    }

    public function setActivation(string $activation): self
    {
        $this->activation = $activation;

        return $this;
    }

    public function getReset(): ?string
    {
        return $this->reset;
    }

    public function setReset(?string $reset): self
    {
        $this->reset = $reset;

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Test;
use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use PHPMailer\PHPMailer\PHPMailer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\FormError;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class UserController extends AbstractController
{

    /**
     * @Route("/users", name="user_index", methods={"GET"})
     */
    public function index(UserRepository $uRepositor ): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $uRepositor->findAll(),
        ]);
    }
    /**
     * @Route("/user/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserPasswordEncoderInterface $passwordEncoder, \Swift_Mailer $mailer, ValidatorInterface $validator): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        $errorsString='';

        if ($form->isSubmitted() && $form->isValid()) {
            $User = $this->getDoctrine()->getManager()->getRepository(User::class)->findOneBy(['email' => strtolower($form->get('email')->getData())]);
            if ($User != null) {
                $form->addError(new FormError('account_password_reset_error_unique'));
            } else {
                $password = $form->get('password')->getData();
                $user->setPassword(
                    $passwordEncoder->encodePassword(
                        $user,
                        $password
                    )
                );
                $user->setEmail(strtolower($form->get('email')->getData()));
                $user->setActivation(uniqid('', true));
                $user->setRoles(['ROLE_USER']);
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($user);
                $entityManager->flush();

//                $mail = new PHPMailer;
//                $mail->isSMTP();
//                $mail->Host = 'smtp.mailgun.org';
//                $mail->SMTPAuth = true;
//                $mail->Username = 'postmaster@sandbox78c68edf3c3949e1b35104d8ee44d6dc.mailgun.org'; // SMTP username
//                $mail->Password = 'f9946013d0d7e4df001d4131924249b1-87cdd773-e140eb23';             // SMTP password
//                $mail->SMTPSecure = 'tls';
//                $mail->setLanguage('lt');
//                $mail->isHTML(true);
//
//                $mail->From = 'noreply@sandbox78c68edf3c3949e1b35104d8ee44d6dc.mailgun.org';
//                $mail->FromName = 'KTU-ETS';
//                $mail->addAddress($user->getEmail());
//
//                $mail->Subject = "Hello!";
//                $mail->Body = $this->renderView('user/emails/registration.html.twig',
//                    [
//                        'user' => $user,
//                    ]
//                );
//                if (!$mail->send()) {
//                    $this->addFlash('danger', 'account_mail_error');
//                } else {
//                    $this->addFlash('success', 'user.flash_message.created');
//                }
//                return $this->redirectToRoute('user_index');
                return $this->redirectToRoute('registration_confirm', ['string' => $user->getActivation()]);
            }
        }
        if ($form->isSubmitted()) {
            if (!$form->isValid()) {
                $pass = $form->get('password')->get('first');
                $passConf = $form->get('password')->get('second');
                if ($pass !== $passConf ) {
                    $form->addError(new FormError('account_password_reset_error_new'));
                }
            }
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/confirmation/{string}", name="registration_confirm", methods={"GET","POST"})
     */
    public function newRegistrationConfirm($string): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        if (null === $User = $entityManager->getRepository(User::class)->findOneBy(['activation'=> $string])) {
            throw $this->createNotFoundException('No user by id '.$User->getId());
        }
        $User->setActivation(1);
        $entityManager->persist($User);
        $entityManager->flush();
        return $this->render('user/registration_confirm.html.twig', [
        ]);
    }

    /**
     * @Route("/user/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $User = $this->getDoctrine()->getManager()->getRepository(User::class)->findOneBy(['email' => strtolower($form->get('email')->getData())]);
            if ($User != null) {
                $this->addFlash('danger', 'account_password_reset_error_unique');
            } else {
                $password = $form->get('password')->getData();
                if ($password != null) {
                    $user->setPassword(
                        $passwordEncoder->encodePassword(
                            $user,
                            $password
                        )
                    );
                }
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($user);
                $entityManager->flush();

                $this->addFlash('success', 'user.flash_message.edited');
            }
            return $this->redirectToRoute('user_index');
        }
        if ($form->isSubmitted()) {
            if (!$form->isValid()) {
                $pass = $form->get('password')->get('first');
                $passConf = $form->get('password')->get('second');
                if ($pass !== $passConf ) {
                    $form->addError(new FormError('account_password_reset_error_new'));
                }
            }
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/user/{id}/delete", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();

            $questions = $user->getQuestions();
            foreach ($questions as $question){
                $question->setFkUser(null);
                $entityManager->persist($question);
                $entityManager->flush();
            }

            $tests = $user->getTests();
            foreach ($tests as $test){
                $test->setFkUser(null);
                $entityManager->persist($test);
                $entityManager->flush();
            }

            $entityManager->remove($user);
            $entityManager->flush();
            $this->addFlash('warning', 'user.flash_message.deleted');
        }
        return $this->redirectToRoute('user_index');
    }

    /**
     * @Route("/passwordreset", name="user_reset_password", methods={"GET","POST"})
     */
    public function resetPassword(Request $request, \Swift_Mailer $mailer) : Response
    {
        $user = new User();
        $form = $this->createFormBuilder($user)
            ->setAction($this->generateUrl('user_reset_password'))
            ->setMethod('POST')
            ->add('email', EmailType::class, [
                'label' => 'account_password_reset_email',
                'attr' => ['placeholder' => 'account_password_reset_email_placeholder'],
                'required' => true,
            ])
            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $email = $form->get('email')->getData();

            $entityManager = $this->getDoctrine()->getManager();
            if (null === $User = $entityManager->getRepository(User::class)->findOneBy(['email' => $email])) {
                $form->addError(new FormError('account_password_reset_error'));
            }
            if ($User != null) {
                $User->setReset(uniqid('', true));
                $entityManager->persist($User);
                $entityManager->flush();

//                $mail = new PHPMailer;
//                $mail->isSMTP();
//                $mail->Host = 'smtp.mailgun.org';
//                $mail->SMTPAuth = true;
//                $mail->Username = 'postmaster@sandbox78c68edf3c3949e1b35104d8ee44d6dc.mailgun.org'; // SMTP username
//                $mail->Password = 'f9946013d0d7e4df001d4131924249b1-87cdd773-e140eb23';             // SMTP password
//                $mail->SMTPSecure = 'tls';
//                $mail->setLanguage('lt');
//                $mail->isHTML(true);
//
//                $mail->From = 'noreply@sandbox78c68edf3c3949e1b35104d8ee44d6dc.mailgun.org';
//                $mail->FromName = 'KTU-ETS';
//                $mail->addAddress($User->getEmail());
//
//                $mail->Subject = "Password reset";
//                $mail->Body    =   $this->renderView('user/emails/password.html.twig',

templates/user/_delete_form.html.twig
<form class="w-49-5" method="post" action="{{ path('user_delete', {'id': user.id}) }}">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-block btn-outline-danger btn-no-right-radius">{{ 'button.delete'|trans }}</button>
</form>
<button data-dismiss="modal" class="w-49-5 btn btn-block btn-primary btn-no-left-radius">{{ 'button.cancel'|trans }}</button>

templates/user/_form.html.twig
{{ form_start(form, { 'attr': { 'id':'user_form', 'class':'needs-validation', 'novalidate':''}}) }}
<div class="accordion">
    <div class="card bg-light">
        <div class="card-header bg-transparent p-0" id="list-general">
            <h2 class="mb-0">
                <button class="btn btn-link btn-block text-left text-decoration-none text-dark card-collapse p-card" type="button" data-toggle="collapse" data-target="#home" aria-expanded="true" aria-controls="home">
                    <i id="attributeCaret1" class="fa fa-caret-down transition"></i>
                    <span class="pl-2">{{ 'general'|trans }} <b class="px-2" data-toggle="tooltip" data-placement="right" title="{{ 'requied'|trans }}">*</b></span>
                </button>
            </h2>
        </div>
        <div id="home" class="tab-pane show" aria-labelledby="list-general list-general-list">
            <div class="card-body">
                <div class="form-group row">
                    {{ form_label(form.email, 'user.form.email_type'|trans ~ ' *', { 'label_attr': { 'class':'col-sm-12 col-form-label'} }) }}
                    <div class="col-sm-12">
                        {% if (app.request.get('_route') == 'user_edit') %}
                            {{ form_widget(form.email, { 'attr': { 'class':'form-control', 'readonly' : 'readonly'} }) }}
                        {% else %}
                            {{ form_widget(form.email, { 'attr': { 'class':'form-control'} }) }}
                        {% endif %}
                        <div class="invalid-feedback ">
                            {{ 'user.validation.email'|trans }}
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    {{ form_label(form.name, 'user.form.name_label'|trans ~ ' *', { 'label_attr': { 'class':'col-sm-12 col-form-label'} }) }}
                    <div class="col-sm-12">
                        {{ form_widget(form.name, { 'attr': { 'class':'form-control'} }) }}
                        <div class="invalid-feedback ">
                            {{ 'user.validation.name'|trans }}
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    {{ form_label(form.last_name, 'user.form.last_name_label'|trans ~ ' *', { 'label_attr': { 'class':'col-sm-12 col-form-label'} }) }}
                    <div class="col-sm-12">
                        {{ form_widget(form.last_name, { 'attr': { 'class':'form-control'} }) }}
                        <div class="invalid-feedback ">
                            {{ 'user.validation.last_name'|trans }}
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    {{ form_label(form.phone, 'user.form.phone_label'|trans ~ ' *', { 'label_attr': { 'class':'col-sm-12 col-form-label'} }) }}
                    <div class="col-sm-12">
                        {{ form_widget(form.phone, { 'attr': { 'class':'form-control'} }) }}
                        <div class="invalid-feedback ">
                            {{ 'user.validation.phone'|trans }}
                        </div>
                    </div>
                </div>

                {% if (app.request.get('_route') == 'user_edit') and app.user.id == user.id or (app.request.get('_route') == 'user_new') %}
                    <div class="border-grey-separator mb-4"></div>
                    <div class="form-group row">
                        {{ form_label(form.password.first, 'user.form.password'|trans ~ ' *', { 'label_attr': { 'class':'col-sm-12 col-form-label'} }) }}
                        <div class="col-sm-12">
                            {% if (app.request.get('_route') == 'user_new') %}
                                {{ form_widget(form.password.first, { 'attr': { 'class':'form-control', 'required':'required'  } }) }}
                            {% else %}
                                {{ form_widget(form.password.first, { 'attr': { 'class':'form-control'  } }) }}
                            {% endif %}
                            <div class="invalid-feedback ">
                                {{ 'user.validation.password'|trans }}
                            </div>
                            <small class="form-text text-muted">
                                {{ 'user.form.password_help'|trans }}
                            </small>
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ form_label(form.password.second, 'user.form.repeated_password'|trans ~ ' *', { 'label_attr': { 'class':'col-sm-12 col-form-label'} }) }}
                        <div class="col-sm-12">
                            {% if (app.request.get('_route') == 'user_new') %}
                                {{ form_widget(form.password.second, { 'attr': { 'class':'form-control', 'required':'required'  } }) }}
                            {% else %}
                                {{ form_widget(form.password.second, { 'attr': { 'class':'form-control'  } }) }}
                            {% endif %}
                            <div class="invalid-feedback ">
                                {{ 'user.validation.password'|trans }}
                            </div>
                            <small class="form-text text-muted">
                                {{ 'user.form.password_help'|trans }}
                            </small>
                        </div>
                    </div>
                {% else %}
                    {{ form_widget(form.password.first, { 'attr': { 'class':'display-hidden'  } }) }}
                    {{ form_widget(form.password.second, { 'attr': { 'class':'display-hidden'  } }) }}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="card border-light">
        <div class="card-header bg-transparent p-0" id="list-save">
            <h2 class="mb-0">
                {% if (app.request.get('_route') == 'user_edit') and app.user.id == user.id or (app.request.get('_route') == 'user_new') %}
                    <button class="btn btn-block btn-primary btn-save btn-no-top-radius" type="submit">{{ button_label|default('Save')|trans  }}</button>
                {% else %}
                    <button class="btn btn-block btn-primary btn-save btn-no-top-radius disabled" disabled>{{ button_label|default('Save')|trans  }}</button>
                {% endif %}
            </h2>
        </div>
    </div>
</div>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'admin.html.twig' %}

{% block title %} {{ 'user.title.edit'|trans }} | ETS{% endblock %}

{% block admin_right_nav %}
    <ul class="section-nav">
        <li class="toc-entry">
            <p>{{ 'side_nav.navigation'|trans }}:</p>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-general" data-target="#home" data-target-animation="#userCaret1" aria-controls="home">{{ 'general'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-save">{{ 'button.save'|trans }}</a>
        </li>
        <div class="my-3"></div>

        <li class="toc-entry">
            <a href="" data-toggle="modal" data-target="#userModal{{ user.id }}Delete" class="modal-append-show badge badge-danger text-white py-1">{{ 'user.button.delete'|trans }}</a>

            <div class="modal fade" id="userModal{{ user.id }}Delete" tabindex="-1" role="dialog" aria-labelledby="userModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="userModalLabel">{{ 'user.delete_message'|trans }}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-footer">
                            <div class="w-100 d-flex justify-content-between">
                                {{ include('user/_delete_form.html.twig') }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </li>
    </ul>
{% endblock %}

{% block admin_main %}

    <h1>{{ 'user.title.edit'|trans }}</h1>
    {{ include('user/_form.html.twig', {'button_label': 'button.save'|trans}) }}

{% endblock %}

templates/user/index.html.twig
{% extends 'admin.html.twig' %}

{% block title %} {{ 'user.title.index'|trans }} | ETS{% endblock %}


    {% block admin_right_nav %}
    {% endblock %}

    {% block admin_main %}

        <h1 class="d-inline float-left">{{ 'user.title.index'|trans }}</h1>
        <span class="float-right mt-1" style="max-width: 75%">
        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="alert alert-{{ label }}">
                    <button type="button" class=" close" data-dismiss="alert" aria-label="Close">
                        <span class="pl-2" aria-hidden="true">&times;</span>
                    </button>
                    <span class='alert-message'>{{ message|trans }}</span>
                </div>
            {% endfor %}
        {% endfor %}
        </span>
        <div class="float-none"></div>

        <div class="table-responsive table-header-sticky">
            <table id="tableheader" class="table table-borderless bg-blue mb-0 text-white table-header table-index">
                <thead>
                <tr>
                    <th scope="col">
                        <span>{{ 'user.form.email_type'|trans }}</span>
                    </th>
                    <th scope="col">
                        <span>{{ 'user.form.name_label'|trans }}</span>
                    </th>
                    <th scope="col">
                        <span>{{ 'user.form.last_name_label'|trans }}</span>
                    </th>
                    <th scope="col">
                        <span>{{ 'user.form.phone_label'|trans }}</span>
                    </th>
                    <th scope="col">{{ 'actions'|trans }}</th>
                </tr>
                </thead>
            </table>
        </div>
        <div class="table-responsive">
            <table class="table table-borderless mb-0 table-index">
                <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.email|trans }}</td>
                        <td>{{ user.name }}</td>
                        <td>{{ user.lastName }}</td>
                        <td>{{ user.phone }}</td>
                        <td class="d-flex justify-content-around">
                            <a data-toggle="tooltip" data-placement="right" title="{{ 'poppers.edit'|trans }}"  href="{{ path('user_edit', {'id': user.id}) }}"><i class="fa fa-pencil"></i></a>
                            <a data-tooltip="tooltip" data-placement="right" title="{{ 'poppers.delete'|trans }}"  href="" data-toggle="modal" data-target="#userModal{{ user.id }}Delete"><i class="fa fa-trash"></i></a>

                            <div class="modal fade" id="userModal{{ user.id }}Delete" tabindex="-1" role="dialog" aria-labelledby="userModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="userModalLabel">{{ 'user.delete_message'|trans }}</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="d-flex justify-content-between">
                                                {{ include('user/_delete_form.html.twig') }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>

                {% else %}
                    <tr>
                        <td colspan="4">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    {% endblock %}

templates/user/new.html.twig
{% extends 'admin.html.twig' %}

{% block title %} {{ 'user.title.new'|trans }} | ETS{% endblock %}

{% block admin_right_nav %}
    <ul class="section-nav">
        <li class="toc-entry">
            <p>{{ 'side_nav.navigation'|trans }}:</p>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-general" data-target="#home" data-target-animation="#userCaret1" aria-controls="home">{{ 'general'|trans }}</a>
        </li>
        <li class="toc-entry">
            <a class="btn btn-block btn-link text-left sidebar-collapse" href="#list-save">{{ 'button.new'|trans }}</a>
        </li>
    </ul>
{% endblock %}

{% block admin_main %}

    {% for error in form.vars['errors'] %}
        <div class="py-3 mx-auto w-100 alert alert-danger">
            <button type="button" class=" close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <span class='text-decoration-none alert-message'>
                    {{ error.message|trans }}
            </span>
        </div>
    {% endfor %}
    <h1>{{ 'user.title.new'|trans }}</h1>
    {{ include('user/_form.html.twig', {'button_label': 'button.new'|trans}) }}

{% endblock %}

templates/user/registration_confirm.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ 'main'|trans }} | ETS{% endblock %}

{% block body %}
    {{ include('_form_navbar.html.twig') }}

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12 col-xl-5 mt-25 text-center">
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-12 col-xl-8 text-center">
                <div class="d-flex justify-content-center">
                    <p class="h2 p-form text-success pr-2 pl-0 pointer-default">{{ 'account_confirmed'|trans }}</p>
                    <i class="registration-success px-0 p-2 text-success p-form fa fa-check-circle"></i>
                </div>
            </div>
        </div>
    </div>

{% endblock %}